# set default port depending on operating system
PORT_LINUX ?= /dev/ttyACM0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))

# setup JLink for flashing
JLINK_DEVICE = EFR32MG21AxxxF1024
include $(RIOTMAKE)/tools/jlink.inc.mk

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk
