# This file is automatically generated, and should not be changed. There is
# probably little reason to edit this file anyway, since it should already
# contain all information for the EFR32MG12P family of CPUs.

# Series - Architecture - Flash base - Flash size - SRAM base - SRAM size - Crypto? - TRNG? - Radio?
EFM32_INFO_efr32mg21b020f1024im32  = 1 cortex-m33 0x00000000 0x00100000 0x20000000 0x00018000 1 1 1

