# CPU used by this board
export CPU = msp430f5
export CPU_MODEL = msp430f5438

# set default port depending on operating system
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))
# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# setup flash tool
export OFLAGS = -O ihex
export FLASHER = python $(RIOTBASE)/dist/tools/feuerwhere/tos-bsl4 
export FFLAGS = -c $(PORT) -ep $(HEXFILE)
